services:
  - type: web
    name: baseradar-searcher-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python searcher.py"
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: RPC_URL
        sync: false
      - key: EXECUTION_RPC_URL
        sync: false
      - key: CONTRACT_ADDRESS
        sync: false
      - key: SEARCHER_PRIVATE_KEY
        sync: false
      - key: SEARCHER_ADDRESS
        sync: false

  - type: worker
    name: fillerx-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python tg_bot.py"
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: EXECUTION_RPC_URL
        sync: false
